### PR TITLE
docs(correction): change .NET to C#.

### PR DESCRIPTION
**Pull request by adyavanapalli**
Note that .NET is a framework, rather than a language.

### CODE REVIEW

**Comment by alizain** [comment]
I'm not sure if those implementations use .NET specific APIs. If they do, `.NET` is more accurate than `C#` imho.

@RobThree @fvilers

**Comment by RobThree** [comment]
As long as it's compiled to 'binary'* (used as a [package](https://www.nuget.org/packages/NUlid/), as 99.999% of the users will use it) it doesn't matter in _which_ .Net language it was written, it will work with any .Net project (be it VB.net, F#, C++/CLI, IronPython, ... basically [_any_ language](https://en.wikipedia.org/wiki/List_of_CLI_languages) that has a .Net binding). So the language ~~isn't very relevant~~ is basically irrelevant. And even if you want to include the (C#) source, you can simply add the project to your solution, regardless the language (again, as long as it's a language with a .Net binding) and reference the project and it'll work. So if you ask me I think the `.Net` designation is a much better choice than `C#`. If anything, I'd change the `F#` and `C#` ones (and maybe others I may have overlooked) to `.Net` too (@mcb2001, @lucasschejtman)

\* And if you want to be really pedantic you could say MSIL, nowadays better known as [CIL](https://en.wikipedia.org/wiki/Common_Intermediate_Language).

**Comment by adyavanapalli** [comment]
Ahh, understood. Sounds good!

**Comment by alizain** [comment]
Thanks for that excellent explanation @RobThree

**Pull request closed without merging**
